FROM node:18-alpine

WORKDIR /app

COPY package.json package-lock.json /app/

RUN npm install && \ 
    rm -rf /tmp/* /var/tmp/*
    
COPY  ./docker-utils/entrypoint/docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh

RUN chmod +x /usr/local/bin/docker-entrypoint.sh

COPY . /app

RUN npm run build

EXPOSE 3008

USER node

CMD ["npm", "run", "start:dev"]

